name: test
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [
          '1.15',
          '1.16',
          '1.17',
          '1.18'
        ]

    name: unit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Build
      run: go build -v .
    - name: Test
      run: go test -cover ./...
    - name: Race
      run: go test -race ./...
